let arr = [ 'Джаз', 'Блюз' ];
alert(arr);
arr.push('Рок-н-ролл');
alert(arr);
arr[Math.floor(arr.length/2)] = 'Классика';
alert(arr);
arr.shift();
alert(arr);
arr.unshift('Рэп' , 'Регги');
alert(arr);
